function A_theta = A_q1(eta_i,in2,in3)
%A_Q1
%    A_THETA = A_Q1(ETA_I,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    31-Mar-2020 18:21:33

alpha_1 = in2(3,:);
alpha_2 = in2(4,:);
beta_1 = in2(1,:);
beta_2 = in2(2,:);
phi_1 = in3(1,:);
phi_2 = in3(2,:);
phi_3 = in3(3,:);
t2 = cos(alpha_1);
t3 = cos(beta_1);
t4 = cos(beta_2);
t5 = cos(eta_i);
t6 = cos(phi_1);
t7 = cos(phi_2);
t8 = cos(phi_3);
t9 = sin(alpha_1);
t10 = sin(beta_1);
t11 = sin(beta_2);
t12 = sin(eta_i);
t13 = sin(phi_1);
t14 = sin(phi_2);
t15 = sin(phi_3);
t16 = t5.^2;
A_theta = -cos(alpha_2)-t2.*t3.*t4.*t6.*t7-t4.*t6.*t7.*t9.*t10+t2.*t7.*t8.*t10.*t11-t3.*t7.*t8.*t9.*t11+t2.*t4.*t10.*t12.*t14-t3.*t4.*t9.*t12.*t14-t2.*t4.*t5.*t7.*t10.*t13+t3.*t4.*t5.*t7.*t9.*t13-t2.*t3.*t5.*t8.*t11.*t13+t2.*t6.*t8.*t10.*t11.*t16-t3.*t6.*t8.*t9.*t11.*t16-t2.*t7.*t8.*t10.*t11.*t16+t3.*t7.*t8.*t9.*t11.*t16-t2.*t3.*t11.*t12.*t13.*t15-t5.*t8.*t9.*t10.*t11.*t13-t9.*t10.*t11.*t12.*t13.*t15-t2.*t3.*t5.*t6.*t11.*t14.*t15+t2.*t3.*t6.*t8.*t11.*t12.*t14+t2.*t5.*t6.*t10.*t11.*t12.*t15-t3.*t5.*t6.*t9.*t11.*t12.*t15-t2.*t5.*t7.*t10.*t11.*t12.*t15+t3.*t5.*t7.*t9.*t11.*t12.*t15-t5.*t6.*t9.*t10.*t11.*t14.*t15+t6.*t8.*t9.*t10.*t11.*t12.*t14-t2.*t10.*t11.*t13.*t14.*t15.*t16+t3.*t9.*t11.*t13.*t14.*t15.*t16+t2.*t5.*t8.*t10.*t11.*t12.*t13.*t14-t3.*t5.*t8.*t9.*t11.*t12.*t13.*t14;
