function A_mu_1 = A_q2(eta_i,in2,in3,q_1)
%A_Q2
%    A_MU_1 = A_Q2(ETA_I,IN2,IN3,Q_1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    31-Mar-2020 18:21:38

alpha_1 = in2(3,:);
alpha_2 = in2(4,:);
beta_1 = in2(1,:);
beta_2 = in2(2,:);
phi_1 = in3(1,:);
phi_2 = in3(2,:);
t2 = cos(alpha_1);
t3 = cos(alpha_2);
t4 = cos(beta_1);
t5 = cos(eta_i);
t6 = cos(phi_1);
t7 = cos(phi_2);
t8 = cos(q_1);
t9 = sin(alpha_1);
t10 = sin(alpha_2);
t11 = sin(beta_1);
t12 = sin(eta_i);
t13 = sin(phi_1);
t14 = sin(phi_2);
t15 = sin(q_1);
A_mu_1 = -cos(beta_2)-t2.*t3.*t4.*t6.*t7-t4.*t6.*t7.*t9.*t10+t2.*t3.*t11.*t12.*t14-t2.*t5.*t10.*t14.*t15+t3.*t5.*t9.*t14.*t15+t9.*t10.*t11.*t12.*t14-t2.*t3.*t5.*t7.*t11.*t13-t2.*t6.*t7.*t8.*t10.*t11+t3.*t6.*t7.*t8.*t9.*t11-t2.*t4.*t8.*t10.*t12.*t14+t3.*t4.*t8.*t9.*t12.*t14-t5.*t7.*t9.*t10.*t11.*t13-t2.*t7.*t10.*t12.*t13.*t15+t3.*t7.*t9.*t12.*t13.*t15+t2.*t4.*t5.*t7.*t8.*t10.*t13-t3.*t4.*t5.*t7.*t8.*t9.*t13;
