function B_theta = B_q1(eta_i,beta_1,beta_2,alpha_1,alpha_2,phi_1,phi_2,phi_3)
%B_Q1
%    B_THETA = B_Q1(ETA_I,BETA_1,BETA_2,ALPHA_1,ALPHA_2,PHI_1,PHI_2,PHI_3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    28-Mar-2020 19:08:56

t2 = cos(beta_2);
t3 = cos(eta_i);
t4 = cos(phi_1);
t5 = cos(phi_2);
t6 = cos(phi_3);
t7 = sin(beta_2);
t8 = sin(eta_i);
t9 = sin(phi_1);
t10 = sin(phi_2);
t11 = sin(phi_3);
t12 = t3.^2;
B_theta = sin(alpha_1).*(t2.*t3.*t10-t4.*t7.*t11+t2.*t5.*t8.*t9-t6.*t7.*t9.*t10+t4.*t7.*t11.*t12-t5.*t7.*t11.*t12-t3.*t4.*t6.*t7.*t8+t3.*t5.*t6.*t7.*t8+t6.*t7.*t9.*t10.*t12+t3.*t7.*t8.*t9.*t10.*t11).*2.0;
