function B_theta = B_q1(eta_i,in2,in3)
%B_Q1
%    B_THETA = B_Q1(ETA_I,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    31-Mar-2020 18:21:34

alpha_1 = in2(3,:);
beta_2 = in2(2,:);
phi_1 = in3(1,:);
phi_2 = in3(2,:);
phi_3 = in3(3,:);
t2 = cos(beta_2);
t3 = cos(eta_i);
t4 = cos(phi_1);
t5 = cos(phi_2);
t6 = cos(phi_3);
t7 = sin(beta_2);
t8 = sin(eta_i);
t9 = sin(phi_1);
t10 = sin(phi_2);
t11 = sin(phi_3);
t12 = t3.^2;
B_theta = sin(alpha_1).*(t2.*t3.*t10-t4.*t7.*t11+t2.*t5.*t8.*t9-t6.*t7.*t9.*t10+t4.*t7.*t11.*t12-t5.*t7.*t11.*t12-t3.*t4.*t6.*t7.*t8+t3.*t5.*t6.*t7.*t8+t6.*t7.*t9.*t10.*t12+t3.*t7.*t8.*t9.*t10.*t11).*2.0;
