function B_mu_1 = B_q2(eta_i,in2,in3,q_1)
%B_Q2
%    B_MU_1 = B_Q2(ETA_I,IN2,IN3,Q_1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    31-Mar-2020 18:21:39

alpha_2 = in2(4,:);
beta_1 = in2(1,:);
phi_1 = in3(1,:);
phi_2 = in3(2,:);
t2 = cos(beta_1);
t3 = cos(eta_i);
t4 = cos(phi_2);
t5 = cos(q_1);
t6 = sin(eta_i);
t7 = sin(phi_1);
t8 = sin(phi_2);
t9 = sin(q_1);
B_mu_1 = sin(alpha_2).*(t3.*t5.*t8+t4.*t5.*t6.*t7-t2.*t6.*t8.*t9-t4.*t9.*cos(phi_1).*sin(beta_1)+t2.*t3.*t4.*t7.*t9).*2.0;
