function J_ee = J_ee(phi_1,phi_2,phi_3)
%J_EE
%    J_EE = J_EE(PHI_1,PHI_2,PHI_3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    28-Mar-2020 23:13:42

t2 = cos(phi_1);
t3 = cos(phi_2);
t4 = sin(phi_1);
J_ee = reshape([1.0,0.0,0.0,0.0,t2,t4,sin(phi_2),-t3.*t4,t2.*t3],[3,3]);
