function J = J_ee(in1)
%J_EE
%    J = J_EE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    31-Mar-2020 18:33:47

phi_1 = in1(1,:);
phi_2 = in1(2,:);
t2 = cos(phi_1);
t3 = cos(phi_2);
t4 = sin(phi_1);
J = reshape([1.0,0.0,0.0,0.0,t2,t4,sin(phi_2),-t3.*t4,t2.*t3],[3,3]);
