function J = J_ee(phi_1,phi_2,phi_3)
%J_EE
%    J = J_EE(PHI_1,PHI_2,PHI_3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Mar-2020 15:28:16

t2 = cos(phi_1);
t3 = cos(phi_2);
t4 = sin(phi_1);
J = reshape([1.0,0.0,0.0,0.0,t2,t4,sin(phi_2),-t3.*t4,t2.*t3],[3,3]);
