function J = J_leg(eta_i,in2,in3)
%J_LEG
%    J = J_LEG(ETA_I,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    31-Mar-2020 18:33:44

alpha_1 = in2(3,:);
alpha_2 = in2(4,:);
beta_1 = in2(1,:);
q_1 = in3(1,:);
q_2 = in3(2,:);
t2 = cos(alpha_1);
t3 = cos(alpha_2);
t4 = cos(beta_1);
t5 = cos(eta_i);
t6 = cos(q_1);
t7 = cos(q_2);
t8 = sin(alpha_1);
t9 = sin(alpha_2);
t10 = sin(beta_1);
t11 = sin(eta_i);
t12 = sin(q_1);
t13 = sin(q_2);
J = reshape([t10.*t11,t5.*t10,-t4,t2.*t10.*t11+t5.*t8.*t12+t4.*t6.*t8.*t11,t2.*t5.*t10-t8.*t11.*t12+t4.*t5.*t6.*t8,-t2.*t4+t6.*t8.*t10,t2.*t3.*t10.*t11+t3.*t5.*t8.*t12+t5.*t6.*t9.*t13+t3.*t4.*t6.*t8.*t11+t2.*t5.*t7.*t9.*t12-t7.*t8.*t9.*t10.*t11-t4.*t9.*t11.*t12.*t13+t2.*t4.*t6.*t7.*t9.*t11,t2.*t3.*t5.*t10-t3.*t8.*t11.*t12-t6.*t9.*t11.*t13+t3.*t4.*t5.*t6.*t8-t5.*t7.*t8.*t9.*t10-t2.*t7.*t9.*t11.*t12-t4.*t5.*t9.*t12.*t13+t2.*t4.*t5.*t6.*t7.*t9,-t2.*t3.*t4+t3.*t6.*t8.*t10+t4.*t7.*t8.*t9-t9.*t10.*t12.*t13+t2.*t6.*t7.*t9.*t10],[3,3]);
