function J = J_leg(eta_i,beta_1,beta_2,alpha_1,alpha_2,system_radius,in7)
%J_LEG
%    J = J_LEG(ETA_I,BETA_1,BETA_2,ALPHA_1,ALPHA_2,SYSTEM_RADIUS,IN7)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    30-Mar-2020 00:21:41

q_1 = in7(:,1);
q_2 = in7(:,2);
t2 = cos(alpha_1);
t3 = cos(alpha_2);
t4 = cos(beta_1);
t5 = cos(eta_i);
t6 = cos(q_1);
t7 = cos(q_2);
t8 = sin(alpha_1);
t9 = sin(alpha_2);
t10 = sin(beta_1);
t11 = sin(eta_i);
t12 = sin(q_1);
t13 = sin(q_2);
J = reshape([t10.*t11,t5.*t10,-t4,t2.*t10.*t11+t5.*t8.*t12+t4.*t6.*t8.*t11,t2.*t5.*t10-t8.*t11.*t12+t4.*t5.*t6.*t8,-t2.*t4+t6.*t8.*t10,t2.*t3.*t10.*t11+t3.*t5.*t8.*t12+t5.*t6.*t9.*t13+t3.*t4.*t6.*t8.*t11+t2.*t5.*t7.*t9.*t12-t7.*t8.*t9.*t10.*t11-t4.*t9.*t11.*t12.*t13+t2.*t4.*t6.*t7.*t9.*t11,t2.*t3.*t5.*t10-t3.*t8.*t11.*t12-t6.*t9.*t11.*t13+t3.*t4.*t5.*t6.*t8-t5.*t7.*t8.*t9.*t10-t2.*t7.*t9.*t11.*t12-t4.*t5.*t9.*t12.*t13+t2.*t4.*t5.*t6.*t7.*t9,-t2.*t3.*t4+t3.*t6.*t8.*t10+t4.*t7.*t8.*t9-t9.*t10.*t12.*t13+t2.*t6.*t7.*t9.*t10],[3,3]);
