function phi_ee = R_to_eulXYZ(in1)
%R_TO_EULXYZ
%    PHI_EE = R_TO_EULXYZ(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Apr-2020 11:15:58

r11 = in1(1);
r12 = in1(4);
r13 = in1(7);
r23 = in1(8);
r33 = in1(9);
phi_ee = [-atan2(r23,r33);asin(r13);-atan2(r12,r11)];
