/*
 * File: Forward_kinematics_v2.c
 *
 * MATLAB Coder version            : 4.3
 * C/C++ source code generated on  : 03-Apr-2020 23:52:15
 */

/* Include Files */
#include "Forward_kinematics_v2.h"
#include "Forward_kinematics_v2_data.h"
#include "Forward_kinematics_v2_initialize.h"
#include "H_leg.h"
#include "Inverse_kinematics.h"
#include "fmincon.h"
#include "rt_defines.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_atan2d_snf(double u0, double u1);

/* Function Definitions */

/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_atan2d_snf(double u0, double u1)
{
  double y;
  int b_u0;
  int b_u1;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else if (rtIsInf(u0) && rtIsInf(u1)) {
    if (u0 > 0.0) {
      b_u0 = 1;
    } else {
      b_u0 = -1;
    }

    if (u1 > 0.0) {
      b_u1 = 1;
    } else {
      b_u1 = -1;
    }

    y = atan2(b_u0, b_u1);
  } else if (u1 == 0.0) {
    if (u0 > 0.0) {
      y = RT_PI / 2.0;
    } else if (u0 < 0.0) {
      y = -(RT_PI / 2.0);
    } else {
      y = 0.0;
    }
  } else {
    y = atan2(u0, u1);
  }

  return y;
}

/*
 * Arguments    : const double system_parameters[5]
 *                const double q[4]
 *                double phi[3]
 * Return Type  : void
 */
void Forward_kinematics_v2(const double system_parameters[5], const double q[4],
  double phi[3])
{
  boolean_T b;
  int i;
  double x0[5];
  double x[5];
  double b_q[3];
  double q_0[3];
  double H_1[16];
  int x0_tmp;
  double dv[16];
  if (isInitialized_Forward_kinematics_v2 == false) {
    Forward_kinematics_v2_initialize();
  }

  b = false;
  for (i = 0; i < 5; i++) {
    x0[i] = 0.0;
  }

  for (i = 0; i < 3; i++) {
    if (!b) {
      b_q[0] = 0.0;
      b_q[1] = 0.0;
      b_q[2] = 0.0;
      b = true;
    }

    Inverse_kinematics((((double)i + 1.0) - 1.0) * 2.0 / 3.0 *
                       3.1415926535897931, system_parameters, b_q, q_0);
    if (i + 1 == 1) {
      x0[0] = q_0[2];
    } else {
      x0_tmp = i << 1;
      x0[x0_tmp - 1] = q_0[0];
      x0[x0_tmp] = q_0[2];
    }
  }

  fmincon(system_parameters, q, x0, x);
  b_q[0] = q[0];
  b_q[1] = q[1];
  b_q[2] = x[0];
  H_leg(0.0, system_parameters, b_q, H_1);

  /* R_TO_EULXYZ */
  /*     PHI_EE = R_TO_EULXYZ(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     01-Apr-2020 11:15:58 */
  b_q[0] = q[0];
  b_q[1] = q[1];
  b_q[2] = x[0];
  phi[0] = -rt_atan2d_snf(H_1[9], H_1[10]);
  H_leg(0.0, system_parameters, b_q, dv);
  phi[1] = asin(dv[8]);
  phi[2] = -rt_atan2d_snf(H_1[4], H_1[0]);
}

/*
 * File trailer for Forward_kinematics_v2.c
 *
 * [EOF]
 */
