/*
 * J_leg.c
 *
 * Code generation for function 'J_leg'
 *
 */

/* Include files */
#include "J_leg.h"
#include "Cost_function.h"
#include "mwmathutil.h"
#include "rt_nonfinite.h"

/* Function Definitions */
void J_leg(real_T eta_i, const real_T in2[5], const real_T in3[3], real_T J[9])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T J_tmp;
  real_T b_J_tmp;
  real_T c_J_tmp;
  real_T d_J_tmp;
  real_T e_J_tmp;

  /* J_LEG */
  /*     J = J_LEG(ETA_I,IN2,IN3) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     31-Mar-2020 18:33:44 */
  t2 = muDoubleScalarCos(in2[2]);
  t3 = muDoubleScalarCos(in2[3]);
  t4 = muDoubleScalarCos(in2[0]);
  t5 = muDoubleScalarCos(eta_i);
  t6 = muDoubleScalarCos(in3[0]);
  t7 = muDoubleScalarCos(in3[1]);
  t8 = muDoubleScalarSin(in2[2]);
  t9 = muDoubleScalarSin(in2[3]);
  t10 = muDoubleScalarSin(in2[0]);
  t11 = muDoubleScalarSin(eta_i);
  t12 = muDoubleScalarSin(in3[0]);
  t13 = muDoubleScalarSin(in3[1]);
  J[0] = t10 * t11;
  J[1] = t5 * t10;
  J[2] = -t4;
  J[3] = (t2 * t10 * t11 + t5 * t8 * t12) + t4 * t6 * t8 * t11;
  J_tmp = t2 * t5;
  b_J_tmp = t4 * t5;
  J[4] = (J_tmp * t10 - t8 * t11 * t12) + b_J_tmp * t6 * t8;
  J[5] = -t2 * t4 + t6 * t8 * t10;
  c_J_tmp = t2 * t3;
  d_J_tmp = t3 * t4;
  e_J_tmp = t2 * t4;
  J[6] = ((((((c_J_tmp * t10 * t11 + t3 * t5 * t8 * t12) + t5 * t6 * t9 * t13) +
             d_J_tmp * t6 * t8 * t11) + J_tmp * t7 * t9 * t12) - t7 * t8 * t9 *
           t10 * t11) - t4 * t9 * t11 * t12 * t13) + e_J_tmp * t6 * t7 * t9 *
    t11;
  J[7] = ((((((c_J_tmp * t5 * t10 - t3 * t8 * t11 * t12) - t6 * t9 * t11 * t13)
             + d_J_tmp * t5 * t6 * t8) - t5 * t7 * t8 * t9 * t10) - t2 * t7 * t9
           * t11 * t12) - b_J_tmp * t9 * t12 * t13) + e_J_tmp * t5 * t6 * t7 *
    t9;
  J[8] = (((-t2 * t3 * t4 + t3 * t6 * t8 * t10) + t4 * t7 * t8 * t9) - t9 * t10 *
          t12 * t13) + t2 * t6 * t7 * t9 * t10;
}

/* End of code generation (J_leg.c) */
