/*
 * File: J_v1.c
 *
 * MATLAB Coder version            : 4.3
 * C/C++ source code generated on  : 01-Apr-2020 17:02:07
 */

/* Include Files */
#include "J_v1.h"
#include "Inverse_kinematics.h"
#include "J_v1_data.h"
#include "J_v1_initialize.h"
#include "rt_nonfinite.h"
#include "svd.h"
#include <math.h>
#include <string.h>

/* Function Definitions */

/*
 * Arguments    : const double system_parameters[5]
 *                const double phi_ee[3]
 *                double J[9]
 * Return Type  : void
 */
void J_v1(const double system_parameters[5], const double phi_ee[3], double J[9])
{
  double t2;
  double t3;
  double t4;
  double t8;
  double t9;
  double t10;
  double q[3];
  double t6;
  double t7;
  double t12;
  double t13;
  double J_gen[27];
  double J_gen_tmp;
  double b_J_gen_tmp;
  double c_J_gen_tmp;
  double d_J_gen_tmp;
  double e_J_gen_tmp;
  double J_gen_tmp_tmp;
  double f_J_gen_tmp;
  double g_J_gen_tmp;
  double h_J_gen_tmp;
  double i_J_gen_tmp;
  double j_J_gen_tmp;
  double k_J_gen_tmp;
  double J_pass[36];
  boolean_T p;
  int br;
  double X[36];
  double U[36];
  double s[6];
  double V[36];
  int i;
  int vcol;
  double b_J_gen[18];
  int r;
  int p3;
  int ar;
  int ib;
  int ia;
  int i1;
  int ic;
  double J_rel[18];
  double J_end[9];
  double x[9];
  double b_J_end[9];
  static const signed char iv[3] = { 1, 0, 0 };

  if (isInitialized_J_v1 == false) {
    J_v1_initialize();
  }

  /*  Jacobian for case when PSM controlled by low links actuators */
  /*  Created by Valeria Skvo */
  t2 = cos(system_parameters[2]);
  t3 = cos(system_parameters[3]);
  t4 = cos(system_parameters[0]);
  t8 = sin(system_parameters[2]);
  t9 = sin(system_parameters[3]);
  t10 = sin(system_parameters[0]);
  Inverse_kinematics(0.0, system_parameters, phi_ee, q);

  /* J_LEG */
  /*     J = J_LEG(ETA_I,IN2,IN3) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     31-Mar-2020 18:33:44 */
  t6 = cos(q[0]);
  t7 = cos(q[1]);
  t12 = sin(q[0]);
  t13 = sin(q[1]);
  J_gen[0] = t10 * 0.0;
  J_gen[1] = t10;
  J_gen[2] = -t4;
  J_gen_tmp = t2 * t10;
  J_gen[3] = (J_gen_tmp * 0.0 + t8 * t12) + t4 * t6 * t8 * 0.0;
  J_gen[4] = (t2 * t10 - t8 * 0.0 * t12) + t4 * t6 * t8;
  b_J_gen_tmp = -t2 * t4;
  J_gen[5] = b_J_gen_tmp + t6 * t8 * t10;
  c_J_gen_tmp = t2 * t3;
  d_J_gen_tmp = t3 * t4;
  e_J_gen_tmp = t2 * t4;
  J_gen_tmp_tmp = c_J_gen_tmp * t10;
  f_J_gen_tmp = t4 * t9;
  g_J_gen_tmp = t3 * t8;
  h_J_gen_tmp = t6 * t9;
  i_J_gen_tmp = d_J_gen_tmp * t6 * t8;
  j_J_gen_tmp = t7 * t8 * t9 * t10;
  k_J_gen_tmp = e_J_gen_tmp * t6 * t7 * t9;
  J_gen[6] = ((((((J_gen_tmp_tmp * 0.0 + g_J_gen_tmp * t12) + h_J_gen_tmp * t13)
                 + i_J_gen_tmp * 0.0) + t2 * t7 * t9 * t12) - j_J_gen_tmp * 0.0)
              - f_J_gen_tmp * 0.0 * t12 * t13) + k_J_gen_tmp * 0.0;
  J_gen[7] = ((((((J_gen_tmp_tmp - g_J_gen_tmp * 0.0 * t12) - h_J_gen_tmp * 0.0 *
                  t13) + i_J_gen_tmp) - j_J_gen_tmp) - t2 * t7 * t9 * 0.0 * t12)
              - t4 * t9 * t12 * t13) + k_J_gen_tmp;
  h_J_gen_tmp = -t2 * t3 * t4;
  i_J_gen_tmp = t9 * t10;
  J_gen[8] = (((h_J_gen_tmp + t3 * t6 * t8 * t10) + t4 * t7 * t8 * t9) -
              i_J_gen_tmp * t12 * t13) + t2 * t6 * t7 * t9 * t10;
  Inverse_kinematics(2.0943951023931953, system_parameters, phi_ee, q);

  /* J_LEG */
  /*     J = J_LEG(ETA_I,IN2,IN3) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     31-Mar-2020 18:33:44 */
  t6 = cos(q[0]);
  t7 = cos(q[1]);
  t12 = sin(q[0]);
  t13 = sin(q[1]);
  J_gen[9] = t10 * 0.86602540378443871;
  J_gen[10] = -0.49999999999999978 * t10;
  J_gen[11] = -t4;
  J_gen[12] = (J_gen_tmp * 0.86602540378443871 + -0.49999999999999978 * t8 * t12)
    + t4 * t6 * t8 * 0.86602540378443871;
  j_J_gen_tmp = t2 * -0.49999999999999978;
  k_J_gen_tmp = t4 * -0.49999999999999978;
  J_gen[13] = (j_J_gen_tmp * t10 - t8 * 0.86602540378443871 * t12) + k_J_gen_tmp
    * t6 * t8;
  J_gen[14] = b_J_gen_tmp + t6 * t8 * t10;
  J_gen[15] = ((((((J_gen_tmp_tmp * 0.86602540378443871 + t3 *
                    -0.49999999999999978 * t8 * t12) + -0.49999999999999978 * t6
                   * t9 * t13) + d_J_gen_tmp * t6 * t8 * 0.86602540378443871) +
                 j_J_gen_tmp * t7 * t9 * t12) - t7 * t8 * t9 * t10 *
                0.86602540378443871) - f_J_gen_tmp * 0.86602540378443871 * t12 *
               t13) + e_J_gen_tmp * t6 * t7 * t9 * 0.86602540378443871;
  J_gen[16] = ((((((c_J_gen_tmp * -0.49999999999999978 * t10 - g_J_gen_tmp *
                    0.86602540378443871 * t12) - t6 * t9 * 0.86602540378443871 *
                   t13) + d_J_gen_tmp * -0.49999999999999978 * t6 * t8) -
                 -0.49999999999999978 * t7 * t8 * t9 * t10) - t2 * t7 * t9 *
                0.86602540378443871 * t12) - k_J_gen_tmp * t9 * t12 * t13) +
    e_J_gen_tmp * -0.49999999999999978 * t6 * t7 * t9;
  J_gen[17] = (((h_J_gen_tmp + t3 * t6 * t8 * t10) + t4 * t7 * t8 * t9) -
               i_J_gen_tmp * t12 * t13) + t2 * t6 * t7 * t9 * t10;
  Inverse_kinematics(4.1887902047863905, system_parameters, phi_ee, q);

  /* J_LEG */
  /*     J = J_LEG(ETA_I,IN2,IN3) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     31-Mar-2020 18:33:44 */
  t6 = cos(q[0]);
  t7 = cos(q[1]);
  t12 = sin(q[0]);
  t13 = sin(q[1]);
  J_gen[18] = t10 * -0.86602540378443849;
  J_gen[19] = -0.50000000000000044 * t10;
  J_gen[20] = -t4;
  J_gen[21] = (J_gen_tmp * -0.86602540378443849 + -0.50000000000000044 * t8 *
               t12) + t4 * t6 * t8 * -0.86602540378443849;
  J_gen_tmp = t2 * -0.50000000000000044;
  j_J_gen_tmp = t4 * -0.50000000000000044;
  J_gen[22] = (J_gen_tmp * t10 - t8 * -0.86602540378443849 * t12) + j_J_gen_tmp *
    t6 * t8;
  J_gen[23] = b_J_gen_tmp + t6 * t8 * t10;
  J_gen[24] = ((((((J_gen_tmp_tmp * -0.86602540378443849 + t3 *
                    -0.50000000000000044 * t8 * t12) + -0.50000000000000044 * t6
                   * t9 * t13) + d_J_gen_tmp * t6 * t8 * -0.86602540378443849) +
                 J_gen_tmp * t7 * t9 * t12) - t7 * t8 * t9 * t10 *
                -0.86602540378443849) - f_J_gen_tmp * -0.86602540378443849 * t12
               * t13) + e_J_gen_tmp * t6 * t7 * t9 * -0.86602540378443849;
  J_gen[25] = ((((((c_J_gen_tmp * -0.50000000000000044 * t10 - g_J_gen_tmp *
                    -0.86602540378443849 * t12) - t6 * t9 * -0.86602540378443849
                   * t13) + d_J_gen_tmp * -0.50000000000000044 * t6 * t8) -
                 -0.50000000000000044 * t7 * t8 * t9 * t10) - t2 * t7 * t9 *
                -0.86602540378443849 * t12) - j_J_gen_tmp * t9 * t12 * t13) +
    e_J_gen_tmp * -0.50000000000000044 * t6 * t7 * t9;
  J_gen[26] = (((h_J_gen_tmp + t3 * t6 * t8 * t10) + t4 * t7 * t8 * t9) -
               i_J_gen_tmp * t12 * t13) + t2 * t6 * t7 * t9 * t10;
  J_pass[0] = J_gen[3];
  J_pass[6] = J_gen[6];
  J_pass[12] = -J_gen[12];
  J_pass[18] = -J_gen[15];
  J_pass[24] = 0.0;
  J_pass[30] = 0.0;
  J_pass[3] = 0.0;
  J_pass[9] = 0.0;
  J_pass[15] = -J_gen[12];
  J_pass[21] = -J_gen[15];
  J_pass[27] = J_gen[21];
  J_pass[33] = J_gen[24];
  J_pass[1] = J_gen[4];
  J_pass[7] = J_gen[7];
  J_pass[13] = -J_gen[13];
  J_pass[19] = -J_gen[16];
  J_pass[25] = 0.0;
  J_pass[31] = 0.0;
  J_pass[4] = 0.0;
  J_pass[10] = 0.0;
  J_pass[16] = -J_gen[13];
  J_pass[22] = -J_gen[16];
  J_pass[28] = J_gen[22];
  J_pass[34] = J_gen[25];
  J_pass[2] = J_gen[5];
  J_pass[8] = J_gen[8];
  J_pass[14] = -J_gen[14];
  J_pass[20] = -J_gen[17];
  J_pass[26] = 0.0;
  J_pass[32] = 0.0;
  J_pass[5] = 0.0;
  J_pass[11] = 0.0;
  J_pass[17] = -J_gen[14];
  J_pass[23] = -J_gen[17];
  J_pass[29] = J_gen[23];
  J_pass[35] = J_gen[26];
  p = true;
  for (br = 0; br < 36; br++) {
    X[br] = 0.0;
    if ((!p) || rtIsNaN(J_pass[br])) {
      p = false;
    }
  }

  if (!p) {
    for (i = 0; i < 36; i++) {
      X[i] = rtNaN;
    }
  } else {
    svd(J_pass, U, s, V);
    t8 = fabs(s[0]);
    if ((!rtIsInf(t8)) && (!rtIsNaN(t8))) {
      if (t8 <= 2.2250738585072014E-308) {
        t8 = 4.94065645841247E-324;
      } else {
        frexp(t8, &vcol);
        t8 = ldexp(1.0, vcol - 53);
      }
    } else {
      t8 = rtNaN;
    }

    t9 = 6.0 * t8;
    r = -1;
    br = 0;
    while ((br < 6) && (s[br] > t9)) {
      r++;
      br++;
    }

    if (r + 1 > 0) {
      vcol = 1;
      for (p3 = 0; p3 <= r; p3++) {
        t8 = 1.0 / s[p3];
        i = vcol + 5;
        for (br = vcol; br <= i; br++) {
          V[br - 1] *= t8;
        }

        vcol += 6;
      }

      for (p3 = 0; p3 <= 30; p3 += 6) {
        i = p3 + 1;
        vcol = p3 + 6;
        if (i <= vcol) {
          memset(&X[i + -1], 0, ((vcol - i) + 1) * sizeof(double));
        }
      }

      br = 0;
      for (p3 = 0; p3 <= 30; p3 += 6) {
        ar = -1;
        br++;
        i = br + 6 * r;
        for (ib = br; ib <= i; ib += 6) {
          ia = ar;
          vcol = p3 + 1;
          i1 = p3 + 6;
          for (ic = vcol; ic <= i1; ic++) {
            ia++;
            X[ic - 1] += U[ib - 1] * V[ia];
          }

          ar += 6;
        }
      }
    }
  }

  for (i = 0; i < 36; i++) {
    X[i] = -X[i];
  }

  b_J_gen[0] = J_gen[0];
  b_J_gen[6] = -J_gen[9];
  b_J_gen[12] = 0.0;
  b_J_gen[3] = 0.0;
  b_J_gen[9] = -J_gen[9];
  b_J_gen[15] = J_gen[18];
  b_J_gen[1] = t10;
  b_J_gen[7] = -J_gen[10];
  b_J_gen[13] = 0.0;
  b_J_gen[4] = 0.0;
  b_J_gen[10] = -J_gen[10];
  b_J_gen[16] = J_gen[19];
  b_J_gen[2] = -t4;
  b_J_gen[8] = t4;
  b_J_gen[14] = 0.0;
  b_J_gen[5] = 0.0;
  b_J_gen[11] = t4;
  b_J_gen[17] = -t4;
  for (i = 0; i < 6; i++) {
    for (vcol = 0; vcol < 3; vcol++) {
      t8 = 0.0;
      for (i1 = 0; i1 < 6; i1++) {
        t8 += X[i + 6 * i1] * b_J_gen[i1 + 6 * vcol];
      }

      J_rel[i + 6 * vcol] = t8;
    }
  }

  /* J_EE */
  /*     J = J_EE(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     31-Mar-2020 18:33:47 */
  t2 = cos(phi_ee[0]);
  t3 = cos(phi_ee[1]);
  t4 = sin(phi_ee[0]);
  J_end[4] = t2;
  J_end[5] = t4;
  t6 = sin(phi_ee[1]);
  J_end[6] = t6;
  t9 = -t3 * t4;
  J_end[7] = t9;
  t8 = t2 * t3;
  J_end[8] = t8;
  J[0] = 1.0;
  J[1] = 0.0;
  J[2] = 0.0;
  J[3] = 0.0;
  J[4] = t2;
  J[5] = t4;
  J[6] = t6;
  J[7] = t9;
  J[8] = t8;
  vcol = 3;
  p3 = 6;
  x[4] = J_end[4];
  x[5] = J_end[5];
  x[7] = J_end[7] - 0.0 * J_end[6];
  x[8] = J_end[8] - 0.0 * J_end[6];
  if (fabs(x[5]) > fabs(x[4])) {
    vcol = 6;
    p3 = 3;
    t8 = x[4];
    x[4] = x[5];
    x[5] = t8;
    t8 = x[7];
    x[7] = x[8];
    x[8] = t8;
  }

  x[5] /= x[4];
  x[8] -= x[5] * x[7];
  t3 = x[5] * 0.0 / x[8];
  t2 = -(x[7] * t3) / x[4];
  J_end[0] = (1.0 - 0.0 * t2) - t6 * t3;
  J_end[1] = t2;
  J_end[2] = t3;
  t3 = -x[5] / x[8];
  t2 = (1.0 - x[7] * t3) / x[4];
  J_end[vcol] = -(0.0 * t2 + t6 * t3);
  J_end[vcol + 1] = t2;
  J_end[vcol + 2] = t3;
  t3 = 1.0 / x[8];
  t2 = -x[7] * t3 / x[4];
  J_end[p3] = -(0.0 * t2 + t6 * t3);
  J_end[p3 + 1] = t2;
  J_end[p3 + 2] = t3;
  for (i = 0; i < 3; i++) {
    t8 = J_end[i + 3];
    t9 = J_end[i + 6];
    for (vcol = 0; vcol < 3; vcol++) {
      b_J_end[i + 3 * vcol] = (J_end[i] * J_gen[3 * vcol] + t8 * J_gen[3 * vcol
        + 1]) + t9 * J_gen[3 * vcol + 2];
    }

    x[3 * i] = iv[i];
    x[3 * i + 1] = J_rel[6 * i];
    x[3 * i + 2] = J_rel[6 * i + 1];
  }

  for (i = 0; i < 3; i++) {
    t8 = b_J_end[i + 3];
    t9 = b_J_end[i + 6];
    for (vcol = 0; vcol < 3; vcol++) {
      J[i + 3 * vcol] = (b_J_end[i] * x[3 * vcol] + t8 * x[3 * vcol + 1]) + t9 *
        x[3 * vcol + 2];
    }
  }
}

/*
 * File trailer for J_v1.c
 *
 * [EOF]
 */
